export const HTTP_ACTION = 'HTTP_ACTION';

export const PRODUCTS = 'PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';

export const FETCH_CART_PRODUCTS = 'FETCH_CART_PRODUCTS';
export const FETCH_CART_PRODUCTS_REQUESTED = 'FETCH_CART_PRODUCTS_REQUESTED';
export const FETCH_CART_PRODUCTS_RECEIVED = 'FETCH_CART_PRODUCTS_RECEIVED';
export const FETCH_CART_PRODUCTS_FAILED = 'FETCH_CART_PRODUCTS_FAILED';
