export const HTTP_ACTION = 'HTTP_ACTION';

export const PRODUCTS = 'PRODUCTS';
export const CART_PRODUCTS = 'CART_PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const CHECK_CART = 'CHECK_CART';

export const FETCH_CART_PRODUCTS = 'FETCH_CART_PRODUCTS';
export const FETCH_CART_PRODUCTS_REQUESTED = 'FETCH_CART_PRODUCTS_REQUESTED';
export const FETCH_CART_PRODUCTS_RECEIVED = 'FETCH_CART_PRODUCTS_RECEIVED';
export const FETCH_CART_PRODUCTS_FAILED = 'FETCH_CART_PRODUCTS_FAILED';

export const SIGNUP = 'SIGNUP';

export const LOGIN = 'LOGIN';

export const LOGOUT = 'LOGOUT';

export const CHECK_USER_TOKEN = 'CHECK_USER_TOKEN';
export const CHECK_USER_TOKEN_FAILED = 'CHECK_USER_TOKEN_FAILED';